apiVersion: v1
kind: PersistentVolume
metadata:
  name: localstorage-pv 
  labels:
    type: local
spec:
  storageClassName: localstorage
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data