name: Docker images form Docker to AWS ECR- Jal Sule.

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Image
    runs-on: ubuntu-latest

    
    steps:
    - uses: actions/checkout@v3     
    - name: Login Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
       
      env: 
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: us-east-1
          
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: k8repo
        IMAGE_TAG: phpGuestbook_1
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 867152996688.dkr.ecr.us-east-1.amazonaws.com
        
        docker build -t k8repo 
        docker tag k8repo:latest 867152996688.dkr.ecr.us-east-1.amazonaws.com/k8repo:latest
